--liquibase formatted sql

--changeset alexp:002-create-payment-cards
CREATE TABLE payment_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    number VARCHAR(19) NOT NULL,
    holder VARCHAR(200) NOT NULL,
    expiration_date DATE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_payment_cards_number UNIQUE (number),
    CONSTRAINT fk_payment_cards_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_payment_cards_user_id ON payment_cards (user_id);
--rollback DROP TABLE payment_cards;
